export const CREATE_ORDER = "CREATE_ORDER";
export const FETCH_ORDER_BEGIN = "FETCH_ORDER_BEGIN";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_ERROR = "FETCH_ORDER_ERROR";
