export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
